### ISSUE TITLE
An error occurred while trying to retrieve information for this media

### ISSUE THREAD

**Issue by wrinkles88** [svbnet/AthamePlugin.Tidal#21]
I know there is the error below me but mine is different.

I downloaded an album yesterday or the day before with no issue now its not working. i did notice my subscription wasn't hifi but like i said it worked 48 hours ago.

[https://imgur.com/a/28BsGo3](url)

**Comment by TripleFrequency** [comment]
First, since you mentioned not having a HiFi subscription, change the plugin settings from Master/Lossless to High. If that doesn't work, try signing out and back into the plugin inside Athame.

**Comment by wrinkles88** [comment]
Ya I had to sing out and back in. Thank you.

On Jun 29, 2018, at 7:16 PM, Michael Haas <notifications@github.com<mailto:notifications@github.com>> wrote:


First, since you mentioned not having a HiFi subscription, change the plugin settings from Master/Lossless to High. If that doesn't work, try signing out and back into the plugin inside Athame.
