### ISSUE TITLE
If you deletes a track in the menu, a unknown error appear

### ISSUE THREAD

**Issue by mcdnlds** [svbnet/AthamePlugin.Tidal#3]
Tidal plugin. windows 7.
im trying to download only a part of a album, but when i delete part of it and try to download, a error box shows, im logged in my tidal hifi account, its okay when i download a full album.

**Comment by hanbang-wang** [comment]
yeah, index error when not downloading first of the list at the beginning.

**Comment by hanbang-wang** [comment]
This is a problem in the main program and I have fixed it by a pull request.
